### PR TITLE
Node-sass with alpine

### PR DESCRIPTION
**Pull request by ice-blaze**
I'm not sure for the ` RUN npm i -g yarn` so I prefer not change it.

I hope it fix the issues. Apparently it's much faster also for building the image.

### CODE REVIEW

**Comment by hitalos** [comment]
Hello @ice-blaze! It's really faster to build, but not install the latest versions. It's for this that I chose to compile.

**Comment by ice-blaze** [comment]
Oh I see, but it's the latest LTS version. Did you found that Laravel need a higher version than the LTS?

**Comment by hitalos** [comment]
Hello @ice-blaze. I'm trying to build with latest LTS version.

**Comment by hitalos** [comment]
`npm install` shows some errors on installing modules.
`yarn` it's installing all modules without errors.

**Comment by hitalos** [comment]
Hello @ice-blaze !!!
Good news! Apparently, this latest updates resolved the problem with node-sass.
Can you try now?

**Comment by ice-blaze** [comment]
Hello, what do you mean with `this` latest update? I'll try as soon as possible but I'm in vacation for still 11 days. Closing it is fine. Only if I have issues in the next days I will update this PR :)

**Comment by ice-blaze** [comment]
@hitalos Good job it works well :+1: 

What about the debian branch? You created it because it solved my issue but now if it works on the `latest` branch, I think we should remove debian branch (we will avoid duplicating states). 

And if someone else comes with a new issue maybe we should recreate the debian branch if it fixes it.

**Pull request closed without merging**
